name: Build and Deploy
on: 
  push:
    branches: 
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.0.4
      with:
        ACCESS_TOKEN: ${{ secrets.todolist }}        
        BUILD_SCRIPT: npm install && npm run build
        BASE_BRANCH: dev # The branch the action should deploy from.
        BRANCH: master # The branch the action should deploy to.
        FOLDER: . # The folder the action should deploy.
